### ISSUE TITLE
RowPro V5.0.7 Changed the CSV File - Parser No Longer Works

### ISSUE THREAD

**Issue by mcgumic** [sanderroosendaal/rowingdata#15]
RowPro came out with a major revision which changed the CSV file such that the CSV parser no longer works. Looks like they are using a more complete date format. 
[rowfile201701011657.zip](https://github.com/sanderroosendaal/rowingdata/files/681416/rowfile201701011657.zip)

**Comment by sanderroosendaal** [comment]
Thanks, and correct. The data format caused the issue. On top of that, there was an additional issue with pandas shifting the columns by one (taking the first column as index). 
Please monitor the time zone of the new file format. It should be better now.
